# Generated by Django 4.1.4 on 2022-12-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
