# Generated by Django 4.1.4 on 2022-12-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='product',
        ),
    ]
