# Generated by Django 4.1.4 on 2022-12-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_review_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
