# Generated by Django 4.1.4 on 2022-12-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
